trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: job1
  steps:
  - script: echo Job1 - Hello, world! Changed
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line scripts'
- job: job2
  dependsOn: job1
  steps:
  - script: echo Job2
    displayName: 'Run a one-line script'
- job: job3
  dependsOn: job2
  steps:
  - script: echo Job3
    displayName: 'Run a one-line script'